package monitordetail

// InverterData - Struct to hold data returned from the Inverter Powerstation API
type MonitorData struct {
	Language string   `json:"language,omitempty"`
	Function []string `json:"function,omitempty"`
	HasError bool     `json:"hasError,omitempty"`
	Msg      string   `json:"msg,omitempty"`
	Code     string   `json:"code,omitempty"`
	Data     struct {
		Kpi struct {
			MonthGeneration float64 `json:"month_generation,omitempty"`
			Pac             float64 `json:"pac,omitempty"`
			Power           float64 `json:"power,omitempty"`
			TotalPower      float64 `json:"total_power,omitempty"`
			DayIncome       float64 `json:"day_income,omitempty"`
			TotalIncome     float64 `json:"total_income,omitempty"`
			YieldRate       float64 `json:"yield_rate,omitempty"`
			Currency        string  `json:"currency,omitempty"`
		} `json:"kpi,omitempty"`
		PowercontrolStatus int   `json:"powercontrol_status,omitempty"`
		Images             []any `json:"images,omitempty"`
		Inverter           []struct {
			IsStored   bool    `json:"is_stored,omitempty"`
			InPac      float64 `json:"in_pac,omitempty"`
			OutPac     float64 `json:"out_pac,omitempty"`
			Eday       float64 `json:"eday,omitempty"`
			Emonth     float64 `json:"emonth,omitempty"`
			Etotal     float64 `json:"etotal,omitempty"`
			Status     int     `json:"status,omitempty"`
			TurnonTime string  `json:"turnon_time,omitempty"`
			Type       string  `json:"type,omitempty"`
			Capacity   float64 `json:"capacity,omitempty"`
			D          struct {
				Capacity              string  `json:"capacity,omitempty"`
				Model                 string  `json:"model,omitempty"`
				OutputPower           string  `json:"output_power,omitempty"`
				OutputCurrent         string  `json:"output_current,omitempty"`
				GridVoltage           string  `json:"grid_voltage,omitempty"`
				BackupOutput          string  `json:"backup_output,omitempty"`
				Soc                   string  `json:"soc,omitempty"`
				Soh                   string  `json:"soh,omitempty"`
				LastRefreshTime       string  `json:"last_refresh_time,omitempty"`
				WorkMode              string  `json:"work_mode,omitempty"`
				DcInput1              string  `json:"dc_input1,omitempty"`
				DcInput2              string  `json:"dc_input2,omitempty"`
				Battery               string  `json:"battery,omitempty"`
				BmsStatus             string  `json:"bms_status,omitempty"`
				Warning               string  `json:"warning,omitempty"`
				ChargeCurrentLimit    string  `json:"charge_current_limit,omitempty"`
				DischargeCurrentLimit string  `json:"discharge_current_limit,omitempty"`
				FirmwareVersion       float64 `json:"firmware_version,omitempty"`
				CreationDate          string  `json:"creationDate,omitempty"`
				EDay                  float64 `json:"eDay,omitempty"`
				ETotal                float64 `json:"eTotal,omitempty"`
				Pac                   float64 `json:"pac,omitempty"`
				HTotal                float64 `json:"hTotal,omitempty"`
				Vpv1                  float64 `json:"vpv1,omitempty"`
				Vpv2                  float64 `json:"vpv2,omitempty"`
				Vpv3                  float64 `json:"vpv3,omitempty"`
				Vpv4                  float64 `json:"vpv4,omitempty"`
				Ipv1                  float64 `json:"ipv1,omitempty"`
				Ipv2                  float64 `json:"ipv2,omitempty"`
				Ipv3                  float64 `json:"ipv3,omitempty"`
				Ipv4                  float64 `json:"ipv4,omitempty"`
				Vac1                  float64 `json:"vac1,omitempty"`
				Vac2                  float64 `json:"vac2,omitempty"`
				Vac3                  float64 `json:"vac3,omitempty"`
				Iac1                  float64 `json:"iac1,omitempty"`
				Iac2                  float64 `json:"iac2,omitempty"`
				Iac3                  float64 `json:"iac3,omitempty"`
				Fac1                  float64 `json:"fac1,omitempty"`
				Fac2                  float64 `json:"fac2,omitempty"`
				Fac3                  float64 `json:"fac3,omitempty"`
				Istr1                 float64 `json:"istr1,omitempty"`
				Istr2                 float64 `json:"istr2,omitempty"`
				Istr3                 float64 `json:"istr3,omitempty"`
				Istr4                 float64 `json:"istr4,omitempty"`
				Istr5                 float64 `json:"istr5,omitempty"`
				Istr6                 float64 `json:"istr6,omitempty"`
				Istr7                 float64 `json:"istr7,omitempty"`
				Istr8                 float64 `json:"istr8,omitempty"`
				Istr9                 float64 `json:"istr9,omitempty"`
				Istr10                float64 `json:"istr10,omitempty"`
				Istr11                float64 `json:"istr11,omitempty"`
				Istr12                float64 `json:"istr12,omitempty"`
				Istr13                float64 `json:"istr13,omitempty"`
				Istr14                float64 `json:"istr14,omitempty"`
				Istr15                float64 `json:"istr15,omitempty"`
				Istr16                float64 `json:"istr16,omitempty"`
			} `json:"d,omitempty"`
			ItChangeFlag bool    `json:"it_change_flag,omitempty"`
			Tempperature float64 `json:"tempperature,omitempty"`
			CheckCode    string  `json:"check_code,omitempty"`
			Next         any     `json:"next,omitempty"`
			Prev         any     `json:"prev,omitempty"`
			NextDevice   struct {
				Sn       any  `json:"sn,omitempty"`
				IsStored bool `json:"isStored,omitempty"`
			} `json:"next_device,omitempty"`
			PrevDevice struct {
				Sn       any  `json:"sn,omitempty"`
				IsStored bool `json:"isStored,omitempty"`
			} `json:"prev_device,omitempty"`
			InvertFull struct {
				CtSolutionType          int     `json:"ct_solution_type,omitempty"`
				Cts                     any     `json:"cts,omitempty"`
				CheckCode               string  `json:"check_code,omitempty"`
				ModelType               string  `json:"model_type,omitempty"`
				ChangeType              int     `json:"change_type,omitempty"`
				ChangeTime              int     `json:"change_time,omitempty"`
				Capacity                float64 `json:"capacity,omitempty"`
				Eday                    float64 `json:"eday,omitempty"`
				Iday                    float64 `json:"iday,omitempty"`
				Etotal                  float64 `json:"etotal,omitempty"`
				Itotal                  float64 `json:"itotal,omitempty"`
				HourTotal               float64 `json:"hour_total,omitempty"`
				Status                  int     `json:"status,omitempty"`
				TurnonTime              int64   `json:"turnon_time,omitempty"`
				Pac                     float64 `json:"pac,omitempty"`
				Tempperature            float64 `json:"tempperature,omitempty"`
				Vpv1                    float64 `json:"vpv1,omitempty"`
				Vpv2                    float64 `json:"vpv2,omitempty"`
				Vpv3                    float64 `json:"vpv3,omitempty"`
				Vpv4                    float64 `json:"vpv4,omitempty"`
				Ipv1                    float64 `json:"ipv1,omitempty"`
				Ipv2                    float64 `json:"ipv2,omitempty"`
				Ipv3                    float64 `json:"ipv3,omitempty"`
				Ipv4                    float64 `json:"ipv4,omitempty"`
				Vac1                    float64 `json:"vac1,omitempty"`
				Vac2                    float64 `json:"vac2,omitempty"`
				Vac3                    float64 `json:"vac3,omitempty"`
				Iac1                    float64 `json:"iac1,omitempty"`
				Iac2                    float64 `json:"iac2,omitempty"`
				Iac3                    float64 `json:"iac3,omitempty"`
				Fac1                    float64 `json:"fac1,omitempty"`
				Fac2                    float64 `json:"fac2,omitempty"`
				Fac3                    float64 `json:"fac3,omitempty"`
				Istr1                   float64 `json:"istr1,omitempty"`
				Istr2                   float64 `json:"istr2,omitempty"`
				Istr3                   float64 `json:"istr3,omitempty"`
				Istr4                   float64 `json:"istr4,omitempty"`
				Istr5                   float64 `json:"istr5,omitempty"`
				Istr6                   float64 `json:"istr6,omitempty"`
				Istr7                   float64 `json:"istr7,omitempty"`
				Istr8                   float64 `json:"istr8,omitempty"`
				Istr9                   float64 `json:"istr9,omitempty"`
				Istr10                  float64 `json:"istr10,omitempty"`
				Istr11                  float64 `json:"istr11,omitempty"`
				Istr12                  float64 `json:"istr12,omitempty"`
				Istr13                  float64 `json:"istr13,omitempty"`
				Istr14                  float64 `json:"istr14,omitempty"`
				Istr15                  float64 `json:"istr15,omitempty"`
				Istr16                  float64 `json:"istr16,omitempty"`
				LastTime                int64   `json:"last_time,omitempty"`
				Vbattery1               float64 `json:"vbattery1,omitempty"`
				Ibattery1               float64 `json:"ibattery1,omitempty"`
				Pmeter                  float64 `json:"pmeter,omitempty"`
				Soc                     float64 `json:"soc,omitempty"`
				Soh                     float64 `json:"soh,omitempty"`
				BmsDischargeIMax        any     `json:"bms_discharge_i_max,omitempty"`
				BmsChargeIMax           float64 `json:"bms_charge_i_max,omitempty"`
				BmsWarning              int     `json:"bms_warning,omitempty"`
				BmsAlarm                int     `json:"bms_alarm,omitempty"`
				BattaryWorkMode         int     `json:"battary_work_mode,omitempty"`
				Workmode                int     `json:"workmode,omitempty"`
				Vload                   float64 `json:"vload,omitempty"`
				Iload                   float64 `json:"iload,omitempty"`
				Firmwareversion         float64 `json:"firmwareversion,omitempty"`
				Bmssoftwareversion      any     `json:"bmssoftwareversion,omitempty"`
				Pbackup                 float64 `json:"pbackup,omitempty"`
				Seller                  float64 `json:"seller,omitempty"`
				Buy                     float64 `json:"buy,omitempty"`
				Yesterdaybuytotal       float64 `json:"yesterdaybuytotal,omitempty"`
				Yesterdaysellertotal    float64 `json:"yesterdaysellertotal,omitempty"`
				Yesterdayct2Sellertotal any     `json:"yesterdayct2sellertotal,omitempty"`
				Yesterdayetotal         any     `json:"yesterdayetotal,omitempty"`
				Yesterdayetotalload     float64 `json:"yesterdayetotalload,omitempty"`
				Yesterdaylastime        int     `json:"yesterdaylastime,omitempty"`
				Thismonthetotle         float64 `json:"thismonthetotle,omitempty"`
				Lastmonthetotle         float64 `json:"lastmonthetotle,omitempty"`
				RAM                     float64 `json:"ram,omitempty"`
				Outputpower             float64 `json:"outputpower,omitempty"`
				FaultMessge             int     `json:"fault_messge,omitempty"`
				Battery1Sn              any     `json:"battery1sn,omitempty"`
				Battery2Sn              any     `json:"battery2sn,omitempty"`
				Battery3Sn              any     `json:"battery3sn,omitempty"`
				Battery4Sn              any     `json:"battery4sn,omitempty"`
				Battery5Sn              any     `json:"battery5sn,omitempty"`
				Battery6Sn              any     `json:"battery6sn,omitempty"`
				Battery7Sn              any     `json:"battery7sn,omitempty"`
				Battery8Sn              any     `json:"battery8sn,omitempty"`
				Pf                      float64 `json:"pf,omitempty"`
				PvPower                 float64 `json:"pv_power,omitempty"`
				ReactivePower           float64 `json:"reactive_power,omitempty"`
				LeakageCurrent          int     `json:"leakage_current,omitempty"`
				IsoLimit                int     `json:"isoLimit,omitempty"`
				Isbuettey               bool    `json:"isbuettey,omitempty"`
				Isbuetteybps            bool    `json:"isbuetteybps,omitempty"`
				Isbuetteybpu            bool    `json:"isbuetteybpu,omitempty"`
				IsESUOREMU              bool    `json:"isESUOREMU,omitempty"`
				BackUpPloadS            float64 `json:"backUpPload_S,omitempty"`
				BackUpVloadS            float64 `json:"backUpVload_S,omitempty"`
				BackUpIloadS            float64 `json:"backUpIload_S,omitempty"`
				BackUpPloadT            float64 `json:"backUpPload_T,omitempty"`
				BackUpVloadT            float64 `json:"backUpVload_T,omitempty"`
				BackUpIloadT            float64 `json:"backUpIload_T,omitempty"`
				ETotalBuy               any     `json:"eTotalBuy,omitempty"`
				EDayBuy                 float64 `json:"eDayBuy,omitempty"`
				EBatteryCharge          any     `json:"eBatteryCharge,omitempty"`
				EChargeDay              float64 `json:"eChargeDay,omitempty"`
				EBatteryDischarge       any     `json:"eBatteryDischarge,omitempty"`
				EDischargeDay           float64 `json:"eDischargeDay,omitempty"`
				BattStrings             any     `json:"battStrings,omitempty"`
				MeterConnectStatus      any     `json:"meterConnectStatus,omitempty"`
				MtActivepowerR          float64 `json:"mtActivepowerR,omitempty"`
				MtActivepowerS          float64 `json:"mtActivepowerS,omitempty"`
				MtActivepowerT          float64 `json:"mtActivepowerT,omitempty"`
				EzProConnectStatus      any     `json:"ezPro_connect_status,omitempty"`
				Dataloggersn            string  `json:"dataloggersn,omitempty"`
				EquipmentName           any     `json:"equipment_name,omitempty"`
				Hasmeter                bool    `json:"hasmeter,omitempty"`
				MeterType               any     `json:"meter_type,omitempty"`
				PreHourLasttotal        any     `json:"pre_hour_lasttotal,omitempty"`
				PreHourTime             any     `json:"pre_hour_time,omitempty"`
				CurrentHourPv           float64 `json:"current_hour_pv,omitempty"`
				ExtendProperties        any     `json:"extend_properties,omitempty"`
				EPConnectStatusHappen   any     `json:"eP_connect_status_happen,omitempty"`
				EPConnectStatusRecover  any     `json:"eP_connect_status_recover,omitempty"`
				TotalSell               float64 `json:"total_sell,omitempty"`
				TotalBuy                float64 `json:"total_buy,omitempty"`
				Errors                  []any   `json:"errors,omitempty"`
				SafetyConutry           float64 `json:"safetyConutry,omitempty"`
				DeratingMode            any     `json:"deratingMode,omitempty"`
				Master                  any     `json:"master,omitempty"`
				ParallelCode            any     `json:"parallel_code,omitempty"`
				InverterType            int     `json:"inverter_type,omitempty"`
				TotalPbattery           float64 `json:"total_pbattery,omitempty"`
				BatteryCount            any     `json:"battery_count,omitempty"`
				MoreBatterys            any     `json:"more_batterys,omitempty"`
				GensetStartMode         any     `json:"genset_start_mode,omitempty"`
				GensetMode              any     `json:"genset_mode,omitempty"`
				GensetEtotal            any     `json:"genset_etotal,omitempty"`
				GensetYeasterdayTotal   any     `json:"genset_yeasterdayTotal,omitempty"`
				GensetPower             any     `json:"genset_power,omitempty"`
				GensetEday              float64 `json:"genset_eday,omitempty"`
				AllEday                 float64 `json:"all_eday,omitempty"`
			} `json:"invert_full,omitempty"`
			Time                     string  `json:"time,omitempty"`
			Battery                  string  `json:"battery,omitempty"`
			FirmwareVersion          float64 `json:"firmware_version,omitempty"`
			WarningBms               string  `json:"warning_bms,omitempty"`
			Soh                      string  `json:"soh,omitempty"`
			DischargeCurrentLimitBms string  `json:"discharge_current_limit_bms,omitempty"`
			ChargeCurrentLimitBms    string  `json:"charge_current_limit_bms,omitempty"`
			Soc                      string  `json:"soc,omitempty"`
			PvInput2                 string  `json:"pv_input_2,omitempty"`
			PvInput1                 string  `json:"pv_input_1,omitempty"`
			BackUpOutput             string  `json:"back_up_output,omitempty"`
			OutputVoltage            string  `json:"output_voltage,omitempty"`
			BackupVoltage            string  `json:"backup_voltage,omitempty"`
			OutputCurrent            string  `json:"output_current,omitempty"`
			OutputPower              string  `json:"output_power,omitempty"`
			TotalGeneration          string  `json:"total_generation,omitempty"`
			DailyGeneration          string  `json:"daily_generation,omitempty"`
			BatteryCharging          string  `json:"battery_charging,omitempty"`
			LastRefreshTime          string  `json:"last_refresh_time,omitempty"`
			BmsStatus                string  `json:"bms_status,omitempty"`
			FaultMessage             string  `json:"fault_message,omitempty"`
			WarningCode              any     `json:"warning_code,omitempty"`
			BatteryPower             float64 `json:"battery_power,omitempty"`
			BackupPloadS             float64 `json:"backup_pload_s,omitempty"`
			BackupVloadS             float64 `json:"backup_vload_s,omitempty"`
			BackupIloadS             float64 `json:"backup_iload_s,omitempty"`
			BackupPloadT             float64 `json:"backup_pload_t,omitempty"`
			BackupVloadT             float64 `json:"backup_vload_t,omitempty"`
			BackupIloadT             float64 `json:"backup_iload_t,omitempty"`
			EtotalBuy                any     `json:"etotal_buy,omitempty"`
			EdayBuy                  float64 `json:"eday_buy,omitempty"`
			EbatteryCharge           any     `json:"ebattery_charge,omitempty"`
			EchargeDay               float64 `json:"echarge_day,omitempty"`
			EbatteryDischarge        any     `json:"ebattery_discharge,omitempty"`
			EdischargeDay            float64 `json:"edischarge_day,omitempty"`
			BattStrings              any     `json:"batt_strings,omitempty"`
			MeterConnectStatus       any     `json:"meter_connect_status,omitempty"`
			MtactivepowerR           float64 `json:"mtactivepower_r,omitempty"`
			MtactivepowerS           float64 `json:"mtactivepower_s,omitempty"`
			MtactivepowerT           float64 `json:"mtactivepower_t,omitempty"`
			HasTigo                  bool    `json:"has_tigo,omitempty"`
			CanStartIV               bool    `json:"canStartIV,omitempty"`
			BatteryCount             any     `json:"battery_count,omitempty"`
		} `json:"inverter,omitempty"`
		Hjgx struct {
			Co2  float64 `json:"co2,omitempty"`
			Tree float64 `json:"tree,omitempty"`
			Coal float64 `json:"coal,omitempty"`
		} `json:"hjgx,omitempty"`
		HomKit struct {
			HomeKitLimit bool `json:"homeKitLimit,omitempty"`
			Sn           any  `json:"sn,omitempty"`
		} `json:"homKit,omitempty"`
		IsTigo                 bool `json:"isTigo,omitempty"`
		TigoIntervalTimeMinute int  `json:"tigoIntervalTimeMinute,omitempty"`
		SmuggleInfo            struct {
			IsAllSmuggle    bool `json:"isAllSmuggle,omitempty"`
			IsSmuggle       bool `json:"isSmuggle,omitempty"`
			DescriptionText any  `json:"descriptionText,omitempty"`
			Sns             any  `json:"sns,omitempty"`
		} `json:"smuggleInfo,omitempty"`
		HasPowerflow              bool `json:"hasPowerflow,omitempty"`
		Powerflow                 any  `json:"powerflow,omitempty"`
		HasGridLoad               bool `json:"hasGridLoad,omitempty"`
		IsParallelInventers       bool `json:"isParallelInventers,omitempty"`
		IsEvCharge                bool `json:"isEvCharge,omitempty"`
		EvCharge                  any  `json:"evCharge,omitempty"`
		HasEnergeStatisticsCharts bool `json:"hasEnergeStatisticsCharts,omitempty"`
		EnergeStatisticsCharts    struct {
			ContributingRate  float64 `json:"contributingRate,omitempty"`
			SelfUseRate       float64 `json:"selfUseRate,omitempty"`
			Sum               float64 `json:"sum,omitempty"`
			Buy               float64 `json:"buy,omitempty"`
			BuyPercent        float64 `json:"buyPercent,omitempty"`
			Sell              float64 `json:"sell,omitempty"`
			SellPercent       float64 `json:"sellPercent,omitempty"`
			SelfUseOfPv       float64 `json:"selfUseOfPv,omitempty"`
			ConsumptionOfLoad float64 `json:"consumptionOfLoad,omitempty"`
			ChartsType        int     `json:"chartsType,omitempty"`
			HasPv             bool    `json:"hasPv,omitempty"`
			HasCharge         bool    `json:"hasCharge,omitempty"`
			Charge            float64 `json:"charge,omitempty"`
			DisCharge         float64 `json:"disCharge,omitempty"`
			GensetGen         float64 `json:"gensetGen,omitempty"`
			HasGenset         bool    `json:"hasGenset,omitempty"`
		} `json:"energeStatisticsCharts,omitempty"`
		EnergeStatisticsTotals struct {
			ContributingRate  float64 `json:"contributingRate,omitempty"`
			SelfUseRate       float64 `json:"selfUseRate,omitempty"`
			Sum               float64 `json:"sum,omitempty"`
			Buy               float64 `json:"buy,omitempty"`
			BuyPercent        float64 `json:"buyPercent,omitempty"`
			Sell              float64 `json:"sell,omitempty"`
			SellPercent       float64 `json:"sellPercent,omitempty"`
			SelfUseOfPv       float64 `json:"selfUseOfPv,omitempty"`
			ConsumptionOfLoad float64 `json:"consumptionOfLoad,omitempty"`
			ChartsType        int     `json:"chartsType,omitempty"`
			HasPv             bool    `json:"hasPv,omitempty"`
			HasCharge         bool    `json:"hasCharge,omitempty"`
			Charge            float64 `json:"charge,omitempty"`
			DisCharge         float64 `json:"disCharge,omitempty"`
			GensetGen         float64 `json:"gensetGen,omitempty"`
			HasGenset         bool    `json:"hasGenset,omitempty"`
		} `json:"energeStatisticsTotals,omitempty"`
		Soc struct {
			Power  int `json:"power,omitempty"`
			Status int `json:"status,omitempty"`
		} `json:"soc,omitempty"`
		Environmental []any `json:"environmental,omitempty"`
		Equipment     []struct {
			Type                 string `json:"type,omitempty"`
			Status               int    `json:"status,omitempty"`
			Model                any    `json:"model,omitempty"`
			StatusText           any    `json:"statusText,omitempty"`
			Capacity             any    `json:"capacity,omitempty"`
			ActionThreshold      any    `json:"actionThreshold,omitempty"`
			SubordinateEquipment string `json:"subordinateEquipment,omitempty"`
			PowerGeneration      string `json:"powerGeneration,omitempty"`
			Eday                 string `json:"eday,omitempty"`
			Brand                string `json:"brand,omitempty"`
			IsStored             bool   `json:"isStored,omitempty"`
			Soc                  string `json:"soc,omitempty"`
			IsChange             bool   `json:"isChange,omitempty"`
			HasTigo              bool   `json:"has_tigo,omitempty"`
			IsSec                bool   `json:"is_sec,omitempty"`
			IsSecs               bool   `json:"is_secs,omitempty"`
			TargetPF             any    `json:"targetPF,omitempty"`
			ExportPowerlimit     any    `json:"exportPowerlimit,omitempty"`
			TitleSn              any    `json:"titleSn,omitempty"`
		} `json:"equipment,omitempty"`
	} `json:"data,omitempty"`
}

func NewMonitorData() *MonitorData {
	return &MonitorData{}
}
